
CC=gcc
CFLAGS=-g -Wall
OBJS=main.o prodotto.o prodotto_negativi.o
BIN = main

all:$(BIN)

main: $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o main


%.o: %.c
	$(CC) $(CFLAGS) -c $^ -o $@

clean:
	rm *.o main



